# CI/CD commands to run as an Azure Pipeline
# https://docs.microsoft.com/azure/devops/pipelines/languages/python

# To select which branches to run *all* tasks on push to remote repo
# trigger:
# - master
# To select which branches to run *all* tasks creating a pull request
# pr:
# - master
# - develop

jobs:
- job: Test

  pool:
    vmImage: 'ubuntu-latest'
  strategy:
    matrix:
      Python36:
        python.version: '3.6'
  
  steps:
  - template: azure_templates/venv_for_package.yml
  - script: |
      . venv/bin/activate
      pytest
    displayName: 'Run tests'
  
- job: Build
  # Condition to only run this job on a specified branch
  condition: eq(variables['Build.SourceBranch'], 'refs/heads/azure_pipeline')

  # Specify that this job depends on another having already run
  dependsOn: Test

  pool:
    vmImage: 'ubuntu-latest'
  strategy:
    matrix:
      Python36:
        python.version: '3.6'
  
  steps:
  - template: azure_templates/venv_for_package.yml
  - script: |
      . venv/bin/activate
      python setup.py sdist bdist_wheel
    displayName: 'Build distributions'
