# CI/CD commands to run as an Azure Pipeline
# https://docs.microsoft.com/azure/devops/pipelines/languages/python

jobs:
- job: Test
  pool:
    vmImage: 'ubuntu-latest'
  strategy:
    matrix:
      Python36:
        python.version: '3.6'
  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '$(python.version)'
    displayName: 'Use Python $(python.version)'

  - script: |
      python -m venv venv
      source venv/bin/activate
      pip install --upgrade pip
    displayName: 'Create venv'

  - script: |
      . venv/bin/activate
      pip install -r requirements.txt
    displayName: 'Install dependencies'

  - script: |
      . venv/bin/activate
      pytest
    displayName: 'Run tests'
  
- job: Build
  # Condition to only run this job on a specified branch
  condition: eq(variables['Build.SourceBranch'], 'refs/heads/basic_tests')

  # Specify that this job depends on another having already run
  dependsOn: Test

  pool:
    vmImage: 'ubuntu-latest'
  strategy:
    matrix:
      Python36:
        python.version: '3.6'
  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '$(python.version)'
    displayName: 'Use Python $(python.version)'

  - script: |
      python -m venv venv
      source venv/bin/activate
      pip install --upgrade pip
    displayName: 'Create venv'

  - script: |
      . venv/bin/activate
      pip install -r requirements.txt
    displayName: 'Install dependencies'

  - script: |
      . venv/bin/activate
      python setup.py sdist bdist_wheel
    displayName: 'Build distributions'
