name: premcon_dev_env
channels:
  - defaults
  - conda-forge
dependencies:
  - python==3.6.6
  - pip==20.0.2
  - jupyter==1.0.0
  - notebook==5.5.0
  - jupyterlab==1.2.6
  - jupytext==1.4.2
  #- pip: 
  #  - -r file:../requirements_dev.txt
